cards = [
    {'manufacturer': 'MSI', 'model': 'GTX', 'model_number': 1000, 'gpu_mgh': 1183, 'memory_interface_bit': 128,
     'gpu_memory_mb': 2048, 'price': 3500,
     'is_sold': False, 'nvidia_graphics_family': True},
    {'manufacturer': 'Asus', 'model': 'GTX', 'model_number': 1040, 'gpu_mgh': 1283, 'memory_interface_bit': 192,
     'gpu_memory_mb': 4096, 'price': 4500,
     'is_sold': False, 'nvidia_graphics_family': True},
    {'manufacturer': 'Gigabyte', 'model': 'GTX', 'model_number': 1050, 'gpu_mgh': 1383,
     'memory_interface_bit': 256,
     'gpu_memory_mb': 6144, 'price': 8500,
     'is_sold': False, 'nvidia_graphics_family': True},
    {'manufacturer': 'Sapphire', 'model': 'GTX', 'model_number': 1060, 'gpu_mgh': 1483,
     'memory_interface_bit': 256,
     'gpu_memory_mb': 8288, 'price': 12500,
     'is_sold': True, 'nvidia_graphics_family': True},
    {'manufacturer': 'Vega', 'model': 'GTX', 'model_number': 1080, 'gpu_mgh': 1583, 'memory_interface_bit': 328,
     'gpu_memory_mb': 16000, 'price': 26000,
     'is_sold': True, 'nvidia_graphics_family': True},
    {'manufacturer': 'MSI', 'model': 'Radeon RX', 'model_number': 550, 'gpu_mgh': 1183, 'memory_interface_bit': 128,
     'gpu_memory_mb': 2048, 'price': 3500,
     'is_sold': False, 'nvidia_graphics_family': False},
    {'manufacturer': 'Asus', 'model': 'Radeon RX', 'model_number': 560, 'gpu_mgh': 1283, 'memory_interface_bit': 192,
     'gpu_memory_mb': 4096, 'price': 4500,
     'is_sold': True, 'nvidia_graphics_family': False},
    {'manufacturer': 'Gigabyte', 'model': 'Radeon RX', 'model_number': 570, 'gpu_mgh': 1383,
     'memory_interface_bit': 256,
     'gpu_memory_mb': 6144, 'price': 8500,
     'is_sold': False, 'nvidia_graphics_family': False},
    {'manufacturer': 'Sapphire', 'model': 'Radeon RX', 'model_number': 580, 'gpu_mgh': 1483,
     'memory_interface_bit': 256,
     'gpu_memory_mb': 8288, 'price': 12500,
     'is_sold': False, 'nvidia_graphics_family': False},
    {'manufacturer': 'Vega', 'model': 'Radeon RX', 'model_number': 600, 'gpu_mgh': 1583, 'memory_interface_bit': 328,
     'gpu_memory_mb': 16000, 'price': 26000,
     'is_sold': True, 'nvidia_graphics_family': False},

]